//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangedMan_Client.WordServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/HangedMan_Server.Model.POCO")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnglishCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpanishCategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnglishCategory {
            get {
                return this.EnglishCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.EnglishCategoryField, value) != true)) {
                    this.EnglishCategoryField = value;
                    this.RaisePropertyChanged("EnglishCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpanishCategory {
            get {
                return this.SpanishCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.SpanishCategoryField, value) != true)) {
                    this.SpanishCategoryField = value;
                    this.RaisePropertyChanged("SpanishCategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://schemas.datacontract.org/2004/07/HangedMan_Server.Model.POCO")]
    [System.SerializableAttribute()]
    public partial class Word : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnglishClueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnglishWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpanishClueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpanishWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WordIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnglishClue {
            get {
                return this.EnglishClueField;
            }
            set {
                if ((object.ReferenceEquals(this.EnglishClueField, value) != true)) {
                    this.EnglishClueField = value;
                    this.RaisePropertyChanged("EnglishClue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnglishWord {
            get {
                return this.EnglishWordField;
            }
            set {
                if ((object.ReferenceEquals(this.EnglishWordField, value) != true)) {
                    this.EnglishWordField = value;
                    this.RaisePropertyChanged("EnglishWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpanishClue {
            get {
                return this.SpanishClueField;
            }
            set {
                if ((object.ReferenceEquals(this.SpanishClueField, value) != true)) {
                    this.SpanishClueField = value;
                    this.RaisePropertyChanged("SpanishClue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpanishWord {
            get {
                return this.SpanishWordField;
            }
            set {
                if ((object.ReferenceEquals(this.SpanishWordField, value) != true)) {
                    this.SpanishWordField = value;
                    this.RaisePropertyChanged("SpanishWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WordID {
            get {
                return this.WordIDField;
            }
            set {
                if ((this.WordIDField.Equals(value) != true)) {
                    this.WordIDField = value;
                    this.RaisePropertyChanged("WordID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordServices.IWordServices")]
    public interface IWordServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetCategories", ReplyAction="http://tempuri.org/IWordServices/GetCategoriesResponse")]
        HangedMan_Client.WordServices.Category[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetCategories", ReplyAction="http://tempuri.org/IWordServices/GetCategoriesResponse")]
        System.Threading.Tasks.Task<HangedMan_Client.WordServices.Category[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetWordsPerCategory", ReplyAction="http://tempuri.org/IWordServices/GetWordsPerCategoryResponse")]
        HangedMan_Client.WordServices.Word[] GetWordsPerCategory(int category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetWordsPerCategory", ReplyAction="http://tempuri.org/IWordServices/GetWordsPerCategoryResponse")]
        System.Threading.Tasks.Task<HangedMan_Client.WordServices.Word[]> GetWordsPerCategoryAsync(int category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetWordSpanish", ReplyAction="http://tempuri.org/IWordServices/GetWordSpanishResponse")]
        string GetWordSpanish(int wordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetWordSpanish", ReplyAction="http://tempuri.org/IWordServices/GetWordSpanishResponse")]
        System.Threading.Tasks.Task<string> GetWordSpanishAsync(int wordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetWordEnglish", ReplyAction="http://tempuri.org/IWordServices/GetWordEnglishResponse")]
        string GetWordEnglish(int wordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetWordEnglish", ReplyAction="http://tempuri.org/IWordServices/GetWordEnglishResponse")]
        System.Threading.Tasks.Task<string> GetWordEnglishAsync(int wordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetClueSpanish", ReplyAction="http://tempuri.org/IWordServices/GetClueSpanishResponse")]
        string GetClueSpanish(int wordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetClueSpanish", ReplyAction="http://tempuri.org/IWordServices/GetClueSpanishResponse")]
        System.Threading.Tasks.Task<string> GetClueSpanishAsync(int wordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetClueEnglish", ReplyAction="http://tempuri.org/IWordServices/GetClueEnglishResponse")]
        string GetClueEnglish(int wordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetClueEnglish", ReplyAction="http://tempuri.org/IWordServices/GetClueEnglishResponse")]
        System.Threading.Tasks.Task<string> GetClueEnglishAsync(int wordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetCategoryByWordID", ReplyAction="http://tempuri.org/IWordServices/GetCategoryByWordIDResponse")]
        string GetCategoryByWordID(int wordID, int matchLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordServices/GetCategoryByWordID", ReplyAction="http://tempuri.org/IWordServices/GetCategoryByWordIDResponse")]
        System.Threading.Tasks.Task<string> GetCategoryByWordIDAsync(int wordID, int matchLanguage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordServicesChannel : HangedMan_Client.WordServices.IWordServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordServicesClient : System.ServiceModel.ClientBase<HangedMan_Client.WordServices.IWordServices>, HangedMan_Client.WordServices.IWordServices {
        
        public WordServicesClient() {
        }
        
        public WordServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HangedMan_Client.WordServices.Category[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<HangedMan_Client.WordServices.Category[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public HangedMan_Client.WordServices.Word[] GetWordsPerCategory(int category) {
            return base.Channel.GetWordsPerCategory(category);
        }
        
        public System.Threading.Tasks.Task<HangedMan_Client.WordServices.Word[]> GetWordsPerCategoryAsync(int category) {
            return base.Channel.GetWordsPerCategoryAsync(category);
        }
        
        public string GetWordSpanish(int wordID) {
            return base.Channel.GetWordSpanish(wordID);
        }
        
        public System.Threading.Tasks.Task<string> GetWordSpanishAsync(int wordID) {
            return base.Channel.GetWordSpanishAsync(wordID);
        }
        
        public string GetWordEnglish(int wordID) {
            return base.Channel.GetWordEnglish(wordID);
        }
        
        public System.Threading.Tasks.Task<string> GetWordEnglishAsync(int wordID) {
            return base.Channel.GetWordEnglishAsync(wordID);
        }
        
        public string GetClueSpanish(int wordID) {
            return base.Channel.GetClueSpanish(wordID);
        }
        
        public System.Threading.Tasks.Task<string> GetClueSpanishAsync(int wordID) {
            return base.Channel.GetClueSpanishAsync(wordID);
        }
        
        public string GetClueEnglish(int wordID) {
            return base.Channel.GetClueEnglish(wordID);
        }
        
        public System.Threading.Tasks.Task<string> GetClueEnglishAsync(int wordID) {
            return base.Channel.GetClueEnglishAsync(wordID);
        }
        
        public string GetCategoryByWordID(int wordID, int matchLanguage) {
            return base.Channel.GetCategoryByWordID(wordID, matchLanguage);
        }
        
        public System.Threading.Tasks.Task<string> GetCategoryByWordIDAsync(int wordID, int matchLanguage) {
            return base.Channel.GetCategoryByWordIDAsync(wordID, matchLanguage);
        }
    }
}
