//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangedMan_Client.PlayerServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/HangedMan_Server.Model.POCO")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsEarnedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthDateField, value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerID {
            get {
                return this.PlayerIDField;
            }
            set {
                if ((this.PlayerIDField.Equals(value) != true)) {
                    this.PlayerIDField = value;
                    this.RaisePropertyChanged("PlayerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsEarned {
            get {
                return this.PointsEarnedField;
            }
            set {
                if ((this.PointsEarnedField.Equals(value) != true)) {
                    this.PointsEarnedField = value;
                    this.RaisePropertyChanged("PointsEarned");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlayerServices.IPlayerServices")]
    public interface IPlayerServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/registerPlayer", ReplyAction="http://tempuri.org/IPlayerServices/registerPlayerResponse")]
        bool registerPlayer(HangedMan_Client.PlayerServices.Player newPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/registerPlayer", ReplyAction="http://tempuri.org/IPlayerServices/registerPlayerResponse")]
        System.Threading.Tasks.Task<bool> registerPlayerAsync(HangedMan_Client.PlayerServices.Player newPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/emailAlreadyRegistered", ReplyAction="http://tempuri.org/IPlayerServices/emailAlreadyRegisteredResponse")]
        bool emailAlreadyRegistered(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/emailAlreadyRegistered", ReplyAction="http://tempuri.org/IPlayerServices/emailAlreadyRegisteredResponse")]
        System.Threading.Tasks.Task<bool> emailAlreadyRegisteredAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/nicknameAlreadyRegistered", ReplyAction="http://tempuri.org/IPlayerServices/nicknameAlreadyRegisteredResponse")]
        bool nicknameAlreadyRegistered(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/nicknameAlreadyRegistered", ReplyAction="http://tempuri.org/IPlayerServices/nicknameAlreadyRegisteredResponse")]
        System.Threading.Tasks.Task<bool> nicknameAlreadyRegisteredAsync(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/telephoneAlreadyExist", ReplyAction="http://tempuri.org/IPlayerServices/telephoneAlreadyExistResponse")]
        bool telephoneAlreadyExist(string telephone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerServices/telephoneAlreadyExist", ReplyAction="http://tempuri.org/IPlayerServices/telephoneAlreadyExistResponse")]
        System.Threading.Tasks.Task<bool> telephoneAlreadyExistAsync(string telephone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerServicesChannel : HangedMan_Client.PlayerServices.IPlayerServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerServicesClient : System.ServiceModel.ClientBase<HangedMan_Client.PlayerServices.IPlayerServices>, HangedMan_Client.PlayerServices.IPlayerServices {
        
        public PlayerServicesClient() {
        }
        
        public PlayerServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool registerPlayer(HangedMan_Client.PlayerServices.Player newPlayer) {
            return base.Channel.registerPlayer(newPlayer);
        }
        
        public System.Threading.Tasks.Task<bool> registerPlayerAsync(HangedMan_Client.PlayerServices.Player newPlayer) {
            return base.Channel.registerPlayerAsync(newPlayer);
        }
        
        public bool emailAlreadyRegistered(string email) {
            return base.Channel.emailAlreadyRegistered(email);
        }
        
        public System.Threading.Tasks.Task<bool> emailAlreadyRegisteredAsync(string email) {
            return base.Channel.emailAlreadyRegisteredAsync(email);
        }
        
        public bool nicknameAlreadyRegistered(string nickname) {
            return base.Channel.nicknameAlreadyRegistered(nickname);
        }
        
        public System.Threading.Tasks.Task<bool> nicknameAlreadyRegisteredAsync(string nickname) {
            return base.Channel.nicknameAlreadyRegisteredAsync(nickname);
        }
        
        public bool telephoneAlreadyExist(string telephone) {
            return base.Channel.telephoneAlreadyExist(telephone);
        }
        
        public System.Threading.Tasks.Task<bool> telephoneAlreadyExistAsync(string telephone) {
            return base.Channel.telephoneAlreadyExistAsync(telephone);
        }
    }
}
