//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangedMan_Client.GameServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://schemas.datacontract.org/2004/07/HangedMan_Server.Model.POCO")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChallengerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateMatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailChallengerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GuestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameChallengerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemainingAttemptsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<char> SelectedLetterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusMatchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WinnerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WordIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChallengerID {
            get {
                return this.ChallengerIDField;
            }
            set {
                if ((this.ChallengerIDField.Equals(value) != true)) {
                    this.ChallengerIDField = value;
                    this.RaisePropertyChanged("ChallengerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateMatch {
            get {
                return this.DateMatchField;
            }
            set {
                if ((object.ReferenceEquals(this.DateMatchField, value) != true)) {
                    this.DateMatchField = value;
                    this.RaisePropertyChanged("DateMatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailChallenger {
            get {
                return this.EmailChallengerField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailChallengerField, value) != true)) {
                    this.EmailChallengerField = value;
                    this.RaisePropertyChanged("EmailChallenger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GuestID {
            get {
                return this.GuestIDField;
            }
            set {
                if ((this.GuestIDField.Equals(value) != true)) {
                    this.GuestIDField = value;
                    this.RaisePropertyChanged("GuestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchID {
            get {
                return this.MatchIDField;
            }
            set {
                if ((this.MatchIDField.Equals(value) != true)) {
                    this.MatchIDField = value;
                    this.RaisePropertyChanged("MatchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchLanguage {
            get {
                return this.MatchLanguageField;
            }
            set {
                if ((this.MatchLanguageField.Equals(value) != true)) {
                    this.MatchLanguageField = value;
                    this.RaisePropertyChanged("MatchLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickNameChallenger {
            get {
                return this.NickNameChallengerField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameChallengerField, value) != true)) {
                    this.NickNameChallengerField = value;
                    this.RaisePropertyChanged("NickNameChallenger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemainingAttempts {
            get {
                return this.RemainingAttemptsField;
            }
            set {
                if ((this.RemainingAttemptsField.Equals(value) != true)) {
                    this.RemainingAttemptsField = value;
                    this.RaisePropertyChanged("RemainingAttempts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<char> SelectedLetter {
            get {
                return this.SelectedLetterField;
            }
            set {
                if ((this.SelectedLetterField.Equals(value) != true)) {
                    this.SelectedLetterField = value;
                    this.RaisePropertyChanged("SelectedLetter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusMatchID {
            get {
                return this.StatusMatchIDField;
            }
            set {
                if ((this.StatusMatchIDField.Equals(value) != true)) {
                    this.StatusMatchIDField = value;
                    this.RaisePropertyChanged("StatusMatchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WinnerID {
            get {
                return this.WinnerIDField;
            }
            set {
                if ((this.WinnerIDField.Equals(value) != true)) {
                    this.WinnerIDField = value;
                    this.RaisePropertyChanged("WinnerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WordID {
            get {
                return this.WordIDField;
            }
            set {
                if ((this.WordIDField.Equals(value) != true)) {
                    this.WordIDField = value;
                    this.RaisePropertyChanged("WordID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameServices.IGameServices")]
    public interface IGameServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/CreateMatch", ReplyAction="http://tempuri.org/IGameServices/CreateMatchResponse")]
        HangedMan_Client.GameServices.Match CreateMatch([System.ServiceModel.MessageParameterAttribute(Name="createMatch")] HangedMan_Client.GameServices.Match createMatch1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/CreateMatch", ReplyAction="http://tempuri.org/IGameServices/CreateMatchResponse")]
        System.Threading.Tasks.Task<HangedMan_Client.GameServices.Match> CreateMatchAsync(HangedMan_Client.GameServices.Match createMatch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetMatchList", ReplyAction="http://tempuri.org/IGameServices/GetMatchListResponse")]
        HangedMan_Client.GameServices.Match[] GetMatchList(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetMatchList", ReplyAction="http://tempuri.org/IGameServices/GetMatchListResponse")]
        System.Threading.Tasks.Task<HangedMan_Client.GameServices.Match[]> GetMatchListAsync(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetMatchesPlayed", ReplyAction="http://tempuri.org/IGameServices/GetMatchesPlayedResponse")]
        HangedMan_Client.GameServices.Match[] GetMatchesPlayed(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetMatchesPlayed", ReplyAction="http://tempuri.org/IGameServices/GetMatchesPlayedResponse")]
        System.Threading.Tasks.Task<HangedMan_Client.GameServices.Match[]> GetMatchesPlayedAsync(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/InitMatch", ReplyAction="http://tempuri.org/IGameServices/InitMatchResponse")]
        bool InitMatch(int guestID, int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/InitMatch", ReplyAction="http://tempuri.org/IGameServices/InitMatchResponse")]
        System.Threading.Tasks.Task<bool> InitMatchAsync(int guestID, int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetGuestNickName", ReplyAction="http://tempuri.org/IGameServices/GetGuestNickNameResponse")]
        string GetGuestNickName(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetGuestNickName", ReplyAction="http://tempuri.org/IGameServices/GetGuestNickNameResponse")]
        System.Threading.Tasks.Task<string> GetGuestNickNameAsync(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/IsThereGuest", ReplyAction="http://tempuri.org/IGameServices/IsThereGuestResponse")]
        bool IsThereGuest(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/IsThereGuest", ReplyAction="http://tempuri.org/IGameServices/IsThereGuestResponse")]
        System.Threading.Tasks.Task<bool> IsThereGuestAsync(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/LeaveMatch", ReplyAction="http://tempuri.org/IGameServices/LeaveMatchResponse")]
        bool LeaveMatch(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/LeaveMatch", ReplyAction="http://tempuri.org/IGameServices/LeaveMatchResponse")]
        System.Threading.Tasks.Task<bool> LeaveMatchAsync(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetGuestLetter", ReplyAction="http://tempuri.org/IGameServices/GetGuestLetterResponse")]
        System.Nullable<char> GetGuestLetter(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetGuestLetter", ReplyAction="http://tempuri.org/IGameServices/GetGuestLetterResponse")]
        System.Threading.Tasks.Task<System.Nullable<char>> GetGuestLetterAsync(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetRemainingAttempts", ReplyAction="http://tempuri.org/IGameServices/GetRemainingAttemptsResponse")]
        int GetRemainingAttempts(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetRemainingAttempts", ReplyAction="http://tempuri.org/IGameServices/GetRemainingAttemptsResponse")]
        System.Threading.Tasks.Task<int> GetRemainingAttemptsAsync(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/UpdatePointsEarned", ReplyAction="http://tempuri.org/IGameServices/UpdatePointsEarnedResponse")]
        void UpdatePointsEarned(int matchID, int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/UpdatePointsEarned", ReplyAction="http://tempuri.org/IGameServices/UpdatePointsEarnedResponse")]
        System.Threading.Tasks.Task UpdatePointsEarnedAsync(int matchID, int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/PenalizeAbandon", ReplyAction="http://tempuri.org/IGameServices/PenalizeAbandonResponse")]
        void PenalizeAbandon(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/PenalizeAbandon", ReplyAction="http://tempuri.org/IGameServices/PenalizeAbandonResponse")]
        System.Threading.Tasks.Task PenalizeAbandonAsync(int playerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/FinishMatch", ReplyAction="http://tempuri.org/IGameServices/FinishMatchResponse")]
        bool FinishMatch(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/FinishMatch", ReplyAction="http://tempuri.org/IGameServices/FinishMatchResponse")]
        System.Threading.Tasks.Task<bool> FinishMatchAsync(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/UpdateCharBD", ReplyAction="http://tempuri.org/IGameServices/UpdateCharBDResponse")]
        bool UpdateCharBD(char letter, int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/UpdateCharBD", ReplyAction="http://tempuri.org/IGameServices/UpdateCharBDResponse")]
        System.Threading.Tasks.Task<bool> UpdateCharBDAsync(char letter, int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetMatchStatus", ReplyAction="http://tempuri.org/IGameServices/GetMatchStatusResponse")]
        int GetMatchStatus(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetMatchStatus", ReplyAction="http://tempuri.org/IGameServices/GetMatchStatusResponse")]
        System.Threading.Tasks.Task<int> GetMatchStatusAsync(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/UpdateRemainingAttempts", ReplyAction="http://tempuri.org/IGameServices/UpdateRemainingAttemptsResponse")]
        bool UpdateRemainingAttempts(int remainingAttempts, int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/UpdateRemainingAttempts", ReplyAction="http://tempuri.org/IGameServices/UpdateRemainingAttemptsResponse")]
        System.Threading.Tasks.Task<bool> UpdateRemainingAttemptsAsync(int remainingAttempts, int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/UpdateWinner", ReplyAction="http://tempuri.org/IGameServices/UpdateWinnerResponse")]
        bool UpdateWinner(int playerID, int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/UpdateWinner", ReplyAction="http://tempuri.org/IGameServices/UpdateWinnerResponse")]
        System.Threading.Tasks.Task<bool> UpdateWinnerAsync(int playerID, int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetWinnerID", ReplyAction="http://tempuri.org/IGameServices/GetWinnerIDResponse")]
        System.Nullable<int> GetWinnerID(int matchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameServices/GetWinnerID", ReplyAction="http://tempuri.org/IGameServices/GetWinnerIDResponse")]
        System.Threading.Tasks.Task<System.Nullable<int>> GetWinnerIDAsync(int matchID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServicesChannel : HangedMan_Client.GameServices.IGameServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServicesClient : System.ServiceModel.ClientBase<HangedMan_Client.GameServices.IGameServices>, HangedMan_Client.GameServices.IGameServices {
        
        public GameServicesClient() {
        }
        
        public GameServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HangedMan_Client.GameServices.Match CreateMatch(HangedMan_Client.GameServices.Match createMatch1) {
            return base.Channel.CreateMatch(createMatch1);
        }
        
        public System.Threading.Tasks.Task<HangedMan_Client.GameServices.Match> CreateMatchAsync(HangedMan_Client.GameServices.Match createMatch) {
            return base.Channel.CreateMatchAsync(createMatch);
        }
        
        public HangedMan_Client.GameServices.Match[] GetMatchList(int playerID) {
            return base.Channel.GetMatchList(playerID);
        }
        
        public System.Threading.Tasks.Task<HangedMan_Client.GameServices.Match[]> GetMatchListAsync(int playerID) {
            return base.Channel.GetMatchListAsync(playerID);
        }
        
        public HangedMan_Client.GameServices.Match[] GetMatchesPlayed(int playerID) {
            return base.Channel.GetMatchesPlayed(playerID);
        }
        
        public System.Threading.Tasks.Task<HangedMan_Client.GameServices.Match[]> GetMatchesPlayedAsync(int playerID) {
            return base.Channel.GetMatchesPlayedAsync(playerID);
        }
        
        public bool InitMatch(int guestID, int matchID) {
            return base.Channel.InitMatch(guestID, matchID);
        }
        
        public System.Threading.Tasks.Task<bool> InitMatchAsync(int guestID, int matchID) {
            return base.Channel.InitMatchAsync(guestID, matchID);
        }
        
        public string GetGuestNickName(int playerID) {
            return base.Channel.GetGuestNickName(playerID);
        }
        
        public System.Threading.Tasks.Task<string> GetGuestNickNameAsync(int playerID) {
            return base.Channel.GetGuestNickNameAsync(playerID);
        }
        
        public bool IsThereGuest(int matchID) {
            return base.Channel.IsThereGuest(matchID);
        }
        
        public System.Threading.Tasks.Task<bool> IsThereGuestAsync(int matchID) {
            return base.Channel.IsThereGuestAsync(matchID);
        }
        
        public bool LeaveMatch(int matchID) {
            return base.Channel.LeaveMatch(matchID);
        }
        
        public System.Threading.Tasks.Task<bool> LeaveMatchAsync(int matchID) {
            return base.Channel.LeaveMatchAsync(matchID);
        }
        
        public System.Nullable<char> GetGuestLetter(int matchID) {
            return base.Channel.GetGuestLetter(matchID);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<char>> GetGuestLetterAsync(int matchID) {
            return base.Channel.GetGuestLetterAsync(matchID);
        }
        
        public int GetRemainingAttempts(int matchID) {
            return base.Channel.GetRemainingAttempts(matchID);
        }
        
        public System.Threading.Tasks.Task<int> GetRemainingAttemptsAsync(int matchID) {
            return base.Channel.GetRemainingAttemptsAsync(matchID);
        }
        
        public void UpdatePointsEarned(int matchID, int playerID) {
            base.Channel.UpdatePointsEarned(matchID, playerID);
        }
        
        public System.Threading.Tasks.Task UpdatePointsEarnedAsync(int matchID, int playerID) {
            return base.Channel.UpdatePointsEarnedAsync(matchID, playerID);
        }
        
        public void PenalizeAbandon(int playerID) {
            base.Channel.PenalizeAbandon(playerID);
        }
        
        public System.Threading.Tasks.Task PenalizeAbandonAsync(int playerID) {
            return base.Channel.PenalizeAbandonAsync(playerID);
        }
        
        public bool FinishMatch(int matchID) {
            return base.Channel.FinishMatch(matchID);
        }
        
        public System.Threading.Tasks.Task<bool> FinishMatchAsync(int matchID) {
            return base.Channel.FinishMatchAsync(matchID);
        }
        
        public bool UpdateCharBD(char letter, int matchID) {
            return base.Channel.UpdateCharBD(letter, matchID);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCharBDAsync(char letter, int matchID) {
            return base.Channel.UpdateCharBDAsync(letter, matchID);
        }
        
        public int GetMatchStatus(int matchID) {
            return base.Channel.GetMatchStatus(matchID);
        }
        
        public System.Threading.Tasks.Task<int> GetMatchStatusAsync(int matchID) {
            return base.Channel.GetMatchStatusAsync(matchID);
        }
        
        public bool UpdateRemainingAttempts(int remainingAttempts, int matchID) {
            return base.Channel.UpdateRemainingAttempts(remainingAttempts, matchID);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRemainingAttemptsAsync(int remainingAttempts, int matchID) {
            return base.Channel.UpdateRemainingAttemptsAsync(remainingAttempts, matchID);
        }
        
        public bool UpdateWinner(int playerID, int matchID) {
            return base.Channel.UpdateWinner(playerID, matchID);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateWinnerAsync(int playerID, int matchID) {
            return base.Channel.UpdateWinnerAsync(playerID, matchID);
        }
        
        public System.Nullable<int> GetWinnerID(int matchID) {
            return base.Channel.GetWinnerID(matchID);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<int>> GetWinnerIDAsync(int matchID) {
            return base.Channel.GetWinnerIDAsync(matchID);
        }
    }
}
